spring:
  application:
    name: finsync-user-service
    jwtSecret: U29tZSBzYW1wbGUgdGV4dCB0byBkZW1vbnN0cmF0ZSBhIHJhbmdlIGVuY29kaW5nIHN0cmluZyBmb3JtYXRzLg==
    jwtSalt: ZW1vbnN0cmF0ZSBhIH
    jwtExpirationMins: 180
    cookieAge: 180
  #config:
  #import: "optional:configserver:http://localhost:8088"
  datasource:
    url: jdbc:postgresql://localhost:5432/finsyncusers
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    user:
      name: admin
      password: 3400
  mail:
    host: smtp.gmail.com
    port: 587
    username: chandramouli@gmail.com
    password: chandramoulipydamalla
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 9001
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
